<?php

/**
 * Implements hook_menu().
 */

function bubblesort_menu() {

  $items = array();

  $items['bubblesort'] = array(
    'title' => 'BubbleSort Simulation',
    'description' => 'BubbleSort creates a bar chart of integers.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bubblesort_form'),
    'access callback' => TRUE
  );
  $items['bubblesort/json'] = array(
    'page callback' => 'bubblesort_json',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['bubblesort/sort'] = array(
    'page callback' => 'bubblesort_sort',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function bubblesort_form($form, &$form_state) {

//  if (isset($form_state['bubblesort'])) {
//    $form['bubblesort'] = $form_state['bubblesort'];
//  }
//  else {
    $form['#theme'] = array('bubblesort_theme');

    $form['#attached']['css'] = array(
      drupal_get_path('module', 'bubblesort') . '/css/bubblesort.css',
    );
    $form['#attached']['js'] = array(
      drupal_get_path('module', 'bubblesort') . '/js/bubblesort.js',
      drupal_get_path('module', 'bubblesort') . '/js/d3.min.js',
    );

    //$form['bubblesort'] = bubblesort_generate($form, $form_state);

    $form['number_integers'] = array(
      '#type' => 'textfield',
      '#title' => t('Number of Integers'),
      '#size' => 2,
      '#maxlength' => 2,
      '#element_validate' => array('element_validate_integer_positive'),
    );
    $form['range_markup'] = array(
      '#markup' => '<p>Enter a range of integers for the BubbleSort Simulation:</p>'
    );
    $form['range_integers_1'] = array(
      '#type' => 'textfield',
      '#title' => t('First Integer'),
      '#size' => 2,
      '#maxlength' => 2,
      '#element_validate' => array('element_validate_integer_positive'),
    );
    $form['range_integers_2'] = array(
      '#type' => 'textfield',
      '#title' => t('Second Integer'),
      '#size' => 2,
      '#maxlength' => 2,
      '#element_validate' => array('element_validate_integer_positive'),
    );

//    $form['bar_chart'] = array(
//      '#markup' => '<div class="chart"></div>',
//    );

    // Simple validation
    $form['#validate'][] = 'bubblesort_form_validate';

    // Submit callbacks for Shuffle and Step
    $form['submit_shuffle'] = array(
      '#type' => 'submit',
      '#value' => t('Shuffle'),
      '#submit' => array('bubblesort_form_submit_shuffle'),
    );
    $form['step_button'] = array(
      '#type' => 'button',
      '#value' => t('Step'),
      '#attributes' => array('onclick' => 'return (false);')
    );
    $form['play_button'] = array(
      '#type' => 'button',
      '#value' => t('Play'),
      '#attributes' => array('onclick' => 'return (false);')
    );

    //$form['#submit'][] = 'bubblesort_form_submit';
//  }
  return $form;
}

function bubblesort_form_validate($form, &$form_state) {
  if ($form_state['values']['number_integers'] == 0) {
    form_set_error('number_integers', 'Number of integers must be greater than 0!"');
  }
  if ($form_state['values']['range_integers_1'] > $form_state['values']['range_integers_2']) {
    form_set_error('range_integers_2', '2nd integer must be greater than 1st integer!"');
  }
  if ($form_state['values']['range_integers_1'] == $form_state['values']['range_integers_2']) {
    form_set_error('range_integers_1', '1st integer and 2nd integer cannot be equal!"');
  }
}

//function bubblesort_form_submit($form, &$form_state) {
//  $form_state['rebuild'] = TRUE;
//}

function bubblesort_sort_callback($form, &$form_state) {
//
//  $stop = 1;
//  return $form['bar_chart'];
}

function bubblesort_form_submit_shuffle($form, &$form_state) {
  $form_state['rebuild'] = TRUE;
}

function bubblesort_form_submit_step($form, &$form_state) {


  //$form_state['rebuild'] = TRUE;
}


/*
 * Implements hook_theme
 */
function bubblesort_theme($existing, $type, $theme, $path) {
  return array(
    'bubblesort_theme' => array(
      'render element' => 'form',
      'template' => 'form--bubblesort',
      'path' => $path . '/templates',
    ),
  );
}
function bubblesort_json($data) {
  if (empty($data)) {
//    $numbers = range(1, 100);
//    shuffle($numbers);
//    $numbers=array_slice($numbers, 0, 10);
    //sort($numbers);
    $numbers = numbers_generate();
  }
  else {
    $data_parts = explode('&', $data);
    foreach($data_parts as $part) {
      $fields[] = explode('=', $part);
    }

    foreach($fields as $field) {
      if (!empty($field[1])) {
        switch ($field[0]) {
          case 'number_integers':
            $total = $field[1];;
            break;
          case 'range_integers_1':
            $range1 = $field[1];
            break;
          case 'range_integers_2':
            $range2 = $field[1];
            break;
        }
      }
      $stop = 1;
    }

//    $numbers = range($range1, $range2);
//    shuffle($numbers);
//    $numbers=array_slice($numbers, 0, $total);
    //sort($numbers);

    $numbers = numbers_generate($total, $range1, $range2, false);

    $stop = 1;
  }
  return drupal_json_output($numbers);
}

function bubblesort_sort($data) {

  $data = explode(',', $data);
  $numbers = numbers_sort($data);
  return drupal_json_output($numbers);
}

function numbers_generate($total = 10, $range1 = 1, $range2 = 100, $sort = FALSE) {
  $numbers = range($range1, $range2);
  shuffle($numbers);
  $numbers=array_slice($numbers, 0, $total);
  if ($sort) {
    rsort($numbers);
  }
  return $numbers;
}

function numbers_sort($values, $start = 0) {
  if ($values[$start] > $values[$start + 1]) {
    $temp = $values[$start];
    $values[$start] = $values[$start + 1];
    $values[$start + 1] = $temp;
  }
  return $values;
}

//function bubblesort_generate($form, &$form_state) {
//
//}